services:
  mosquitto:
    image: eclipse-mosquitto:2
    volumes:
      - ./conf/:/mosquitto/config/:ro
      - ./logs/:/mosquitto/log/
      - data:/mosquitto/data/
    ports:
      - 1883:1883
      - 9001:9001

volumes:
  data: ~